- import some functions from stochopy to test the code

In [1]:
# python lbfgsb works with numpy arrays
import numpy as np
from pyrtid.inverse import minimize_ensemble_lbfgsb
from scipy.optimize import minimize

- First example: min x^{\mathrm{T}}x such that x>=1. Optimal solution hits the boundary.

In [2]:
def quad(x):
    # return x.dot(x)
    return 10 * x[0] ** 2 + x[1] ** 2


def grad_quad(x):
    return np.array([10 * x[0], x[1]])


def fun_and_grad(x):
    return quad(x), grad_quad(x)


ftol = 1e-5
gtol = 1e-5
l = np.array([1.0, 1.0])
u = np.array([np.inf, np.inf])
bounds = np.array((l, u)).T
x0 = np.array([5, 5])

# Perform a normal sampling
x0 = np.random.random(size=[2, 20]) * 4.0 + 3.0

In [3]:
x0

array([[4.12691339, 3.19371666, 5.05331221, 6.48834179, 4.35687922,
        5.85329636, 6.9258633 , 5.79930212, 5.68736878, 6.78241897,
        4.53634845, 3.4821337 , 4.03757061, 5.06122433, 4.54993858,
        3.49364452, 3.52692405, 3.52512476, 4.29932759, 3.13766736],
       [3.40720986, 6.0810578 , 4.60960325, 3.48854977, 5.05154802,
        4.88933519, 5.83186349, 5.3466614 , 4.31001674, 6.79217618,
        5.58124982, 3.58171614, 4.10084471, 5.65670194, 4.99373081,
        6.19652736, 4.87977848, 3.63422808, 6.08385877, 5.88388632]])

In [4]:
bounds[0]

array([ 1., inf])

In [5]:
x0[:, 0]

array([4.12691339, 3.40720986])

### New implementation

In [6]:
print("====================== Quadratic example ======================")
opt_quad = minimize_ensemble_lbfgsb(
    x0=x0,
    fun_and_jac=fun_and_grad,
    bounds=bounds,
    ftol=ftol,
    gtol=gtol,
    iprint=101,
    maxcor=40,
    max_iter=5,
    is_initialize_bfgs_matrices_from_ensemble=True,
)
print("")
print("")
xOpt = np.array([1, 1])
theoOpt = {"x": xOpt, "f": quad(xOpt), "df": grad_quad(xOpt)}

====================== Quadratic example ======================
RUNNING THE L-BFGS-B CODE
           * * *
Machine precision = 2.220446049250313e-16
N = 	2	M = 	40
At X0, 0 variables are exactly at the bounds
At iterate 0 , f= 513.6864558309223 , |proj g|= 5.925863296551872
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
sorted_f before = [513.68645583 506.14572834 433.15577138 366.51638144 364.90583863
 342.03788017 288.15819425 276.60808469 236.93492206 231.95675837
 221.8555151  215.34210276 181.92322049 179.83669185 160.45247173
 148.20417046 138.97752469 137.47265971 134.08124167 133.06968281]
sorted_f = [513.68645583 506.14572834 433.15577138 366.51638144 364.90583863
 342.03788017 288.15819425 276.60808469 236.93492206 231.95675837
 221.8555151  215.34210276 181.92322049 179.83669185 160.45247173
 148.20417046 138.97752469 137.47265971 134.08124167 133.06968281]
L = [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00 

/home/acollet/workspace/pyrtid/pyrtid/inverse/solvers/lbfgsb/lbfgsb_ens.py:396: RuntimeWarning: LinearOperator subclass should implement at least one of _matvec and _matmat.
  mat = EnsembleCovarianceMatrix(np.array(G))



ITERATION 2

F = deque([513.6864558309223, 506.1457283428034, 433.1557713849616, 366.51638144107835, 364.9058386331598, 342.037880172946, 288.1581942483791, 276.60808469154307, 236.9349220648762, 231.95675837013428, 221.85551510219156, 215.34210276021693, 181.92322048739166, 179.83669184836936, 160.45247173026092, 148.20417046352242, 138.9775246920311, 137.4726597141977, 134.08124166947735, 133.06968280928425, 513.6864558309223, 506.1457283428034, 433.1557713849616, 366.51638144107835, 364.9058386331598, 342.037880172946, 288.1581942483791, 276.60808469154307, 236.9349220648762, 231.95675837013428, 221.85551510219156, 215.34210276021693, 181.92322048739166, 179.83669184836936, 160.45247173026092, 148.20417046352242, 138.9775246920311, 137.4726597141977, 134.08124166947735, 133.06968280928425])
X = deque([array([6.9258633 , 5.83186349]), array([6.78241897, 6.79217618]), array([6.48834179, 3.48854977]), array([5.85329636, 4.88933519]), array([5.79930212, 5.3466614 ]), array([5.68736878,


ITERATION 3

F = deque([513.6864558309223, 506.1457283428034, 433.1557713849616, 366.51638144107835, 364.9058386331598, 342.037880172946, 288.1581942483791, 276.60808469154307, 236.9349220648762, 231.95675837013428, 221.85551510219156, 215.34210276021693, 181.92322048739166, 179.83669184836936, 160.45247173026092, 148.20417046352242, 138.9775246920311, 137.4726597141977, 134.08124166947735, 133.06968280928425, 513.6864558309223, 506.1457283428034, 433.1557713849616, 366.51638144107835, 364.9058386331598, 342.037880172946, 288.1581942483791, 276.60808469154307, 236.9349220648762, 231.95675837013428, 221.85551510219156, 215.34210276021693, 181.92322048739166, 179.83669184836936, 160.45247173026092, 148.20417046352242, 138.9775246920311, 137.4726597141977, 134.08124166947735, 133.06968280928425])
X = deque([array([6.9258633 , 5.83186349]), array([6.78241897, 6.79217618]), array([6.48834179, 3.48854977]), array([5.85329636, 4.88933519]), array([5.79930212, 5.3466614 ]), array([5.68736878,

In [7]:
print("Theoretical optimal value: ")
print(theoOpt)
print("Optimal value found: ")
print(opt_quad)

Theoretical optimal value: 
{'x': array([1, 1]), 'f': 11, 'df': array([10,  1])}
Optimal value found: 
  message: START
  success: False
   status: 2
      fun: 133.06968280928425
        x: [[ 4.127e+00  3.194e+00 ...  4.299e+00  3.138e+00]
            [ 3.407e+00  6.081e+00 ...  6.084e+00  5.884e+00]]
      nit: 0
      jac: [[ 4.127e+01  3.194e+01 ...  4.299e+01  3.138e+01]
            [ 3.407e+00  6.081e+00 ...  6.084e+00  5.884e+00]]
     nfev: 20
     njev: 20
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>


In [8]:
opt_quad.x

array([[4.12691339, 3.19371666, 5.05331221, 6.48834179, 4.35687922,
        5.85329636, 6.9258633 , 5.79930212, 5.68736878, 6.78241897,
        4.53634845, 3.4821337 , 4.03757061, 5.06122433, 4.54993858,
        3.49364452, 3.52692405, 3.52512476, 4.29932759, 3.13766736],
       [3.40720986, 6.0810578 , 4.60960325, 3.48854977, 5.05154802,
        4.88933519, 5.83186349, 5.3466614 , 4.31001674, 6.79217618,
        5.58124982, 3.58171614, 4.10084471, 5.65670194, 4.99373081,
        6.19652736, 4.87977848, 3.63422808, 6.08385877, 5.88388632]])

## Second example : min Rosenbrock function

In [9]:
def rosenbrock(x):
    return 100 * (x[1] - x[0] ** 2) ** 2 + (1 - x[0]) ** 2


def grad_rosenbrock(x):
    g = np.empty(x.size)
    g[0] = 400 * x[0] * (x[0] ** 2 - x[1]) + 2 * (x[0] - 1)
    g[1] = 200 * (-x[0] ** 2 + x[1])
    return g


def fun_and_grad_rosenbrock(x):
    return rosenbrock(x), grad_rosenbrock(x)


l = np.array([-2, -2])
u = np.array([2, 2])
bounds = np.array((l, u)).T
# x0 = np.array([0.12, 0.12])
# x0 = np.array([-1, -1])

# x0 = (np.random.random(size=[2, 10]) - 0.5) * 4
x0 = np.random.random(size=[2, 2]) * 0.0 + -1.0

In [10]:
x0

array([[-1., -1.],
       [-1., -1.]])

### New implementation

In [11]:
np.finfo(1.0).resolution * 1e7

1e-08

In [12]:
opt_rosenbrock = minimize_ensemble_lbfgsb(
    x0=x0,
    fun_and_jac=fun_and_grad_rosenbrock,
    bounds=bounds,
    ftol=ftol,
    gtol=gtol,
    iprint=101,
    ftol_linesearch=1e-3,
    gtol_linesearch=0.9,
    xtol_linesearch=0.1,
    is_initialize_bfgs_matrices_from_ensemble=True,
)
print("")
print("")
theoOpt = {"x": np.array([1, 1]), "f": 0, "df": grad_rosenbrock(np.array([1, 1]))}
print("Theoretical optimal value: ")
print(theoOpt)
print("Optimal value found: ")

RUNNING THE L-BFGS-B CODE
           * * *
Machine precision = 2.220446049250313e-16
N = 	2	M = 	10
At X0, 0 variables are exactly at the bounds
At iterate 0 , f= 404.0 , |proj g|= 3.0
[0 1]
sorted_f before = [404. 404.]
sorted_f = [404. 404.]
condition on F not met
F = deque([404.0])
X = deque([array([-1., -1.])])

ITERATION 1

F = deque([404.0])
X = deque([array([-1., -1.])])
x = [-1. -1.]


/home/acollet/workspace/pyrtid/pyrtid/inverse/regularization/covariances.py:320: RuntimeWarning: invalid value encountered in divide
  return np.linalg.multi_dot([self.anomalies.T, self.anomalies, x]) / (


KeyboardInterrupt: 

In [ ]:
print(opt_rosenbrock)

  message: START
  success: False
   status: 2
      fun: 6.011336212076357e-07
        x: [[ 1.000e+00  1.000e+00]
            [ 1.001e+00  1.001e+00]]
      nit: 0
      jac: [[ 2.558e-02  2.558e-02]
            [-1.231e-02 -1.231e-02]]
     nfev: 37
     njev: 37
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>


## Third example : min Beale function

In [14]:
def beale(x):
    return (
        (1.5 - x[0] + x[0] * x[1]) ** 2
        + (2.25 - x[0] + x[0] * x[1] ** 2) ** 2
        + (2.625 - x[0] + x[0] * x[1] ** 3) ** 2
    )


def grad_beale(x):
    y1 = x[1]
    y2 = y1 * y1
    y3 = y2 * y1
    f1 = 1.5 - x[0] + x[0] * y1
    f2 = 2.25 - x[0] + x[0] * y2
    f3 = 2.625 - x[0] + x[0] * y3

    return np.array(
        [
            2 * (y1 - 1) * f1 + 2 * (y2 - 1) * f2 + 2 * (y3 - 1) * f3,
            2 * x[0] * f1 + 4 * x[0] * y1 * f2 + 6 * x[0] * y2 * f3,
        ]
    )


def beale_fun_and_jac(x):
    return beale(x), grad_beale(x)


ftol = 1e-14
gtol = 1e-10
l = -4.5 * np.ones(2)
u = -l
bounds = np.array((l, u)).T
# x0 = np.array([2.5, -1.3])

# Equivalent to the vector version.
# x0 = np.array([[2.5],[-1.3]])

# This is more complex
# x0 = (np.random.random(size=[2, 10]) - 0.5) * 4
ne = 30
x0 = np.zeros((2, ne))
x0[0] = np.random.random(ne) * 2 + 2.0
x0[1] = np.random.random(ne) * 1 - 1.0

In [15]:
x0

array([[ 3.06892363,  3.95908119,  3.50500753,  2.93561658,  2.45373251,
         3.7763075 ,  2.57362673,  3.6812923 ,  2.16837429,  3.36963247,
         2.53521766,  3.52705258,  3.1304042 ,  3.00029069,  2.34885001,
         3.4875092 ,  2.76881897,  3.05669909,  2.08772764,  3.63856801,
         2.51954147,  2.97100058,  3.27201485,  2.73253786,  3.97214418,
         2.5637877 ,  2.70534359,  3.88198055,  2.36844032,  3.78236555],
       [-0.62253996, -0.68008723, -0.4915677 , -0.47415555, -0.47763037,
        -0.70481421, -0.90967047, -0.24249928, -0.65934021, -0.0539378 ,
        -0.50141662, -0.78252695, -0.95996856, -0.63655167, -0.290179  ,
        -0.24366023, -0.90890325, -0.31464346, -0.07387695, -0.09005485,
        -0.22303191, -0.83201079, -0.4672728 , -0.11113677, -0.14724142,
        -0.32394522, -0.18373587, -0.5883357 , -0.30379142, -0.73581555]])

### New implementation

In [16]:
opt_beale = minimize_ensemble_lbfgsb(
    x0=x0,
    fun_and_jac=beale_fun_and_jac,
    bounds=bounds,
    ftol=ftol,
    gtol=gtol,
    maxcor=20,
    is_initialize_bfgs_matrices_from_ensemble=True,
    max_iter=9,
)
print("")
print("")
theoOpt = {
    "x": np.array([3, 0.5]),
    "f": beale(np.array([3, 0.5])),
    "df": grad_beale(np.array([3, 0.5])),
}
print("Theoretical optimal value: ")
print(theoOpt)
print("Optimal value found: ")

[ 0  1  3  4  6  7  9 10 12 13 14 16 17 19 20 22 23 25 26 28 29]
sorted_f before = [36.22911975 33.20731962 33.02296988 30.62327064 30.41442395 26.04599532
 22.39773714 21.56235675 18.47926886 15.74466467 13.87100885 13.64652736
 13.16616381 12.15467228 11.95286479  9.94547107  8.96209056  8.38454995
  6.87442874  5.99515858  5.49641447  5.47824798  4.65464026  3.59110228
  3.04014691  2.57377719  2.56777982  2.52788182  2.39987985  0.8684264 ]
sorted_f = [36.22911975 33.20731962 30.62327064 30.41442395 22.39773714 21.56235675
 15.74466467 13.87100885 13.16616381 12.15467228 11.95286479  8.96209056
  8.38454995  5.99515858  5.49641447  4.65464026  3.59110228  2.57377719
  2.56777982  2.39987985  0.8684264 ]
L = [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+

b'ERROR: INITIAL G .GE. ZERO'
9.945471074181887
[ 3.4875092  -0.24366023]
[ 10.84810288 -17.42166401]
F = deque([33.20731961931172, 30.623270637361877, 30.414423954062222, 22.3977371440853, 21.56235675442705, 15.744664667627513, 13.871008846262509, 13.166163814103609, 12.154672277428856, 11.95286479103905, 8.962090556030326, 8.384549945528935, 5.995158579942398, 5.496414465122279, 4.654640264702227, 3.5911022760127507, 2.5737771901768864, 2.5677798201759585, 2.3998798526770018, 0.8684264036772855])
X = deque([array([ 3.95908119, -0.68008723]), array([ 3.7763075 , -0.70481421]), array([ 3.52705258, -0.78252695]), array([ 2.76881897, -0.90890325]), array([ 2.97100058, -0.83201079]), array([ 3.50500753, -0.4915677 ]), array([ 3.97214418, -0.14724142]), array([ 3.00029069, -0.63655167]), array([ 3.6812923 , -0.24249928]), array([ 3.27201485, -0.4672728 ]), array([ 3.63856801, -0.09005485]), array([ 2.93561658, -0.47415555]), array([ 3.36963247, -0.0539378 ]), array([ 2.53521766, -0.5014166

In [17]:
print(opt_beale)

  message: START
  success: False
   status: 2
      fun: 0.8684264036772855
        x: [[ 3.069e+00  3.959e+00 ...  2.368e+00  3.782e+00]
            [-6.225e-01 -6.801e-01 ... -3.038e-01 -7.358e-01]]
      nit: 0
      jac: [[ 1.378e+01  2.396e+01 ...  3.568e+00  2.456e+01]
            [-3.264e+01 -7.045e+01 ... -7.561e+00 -7.679e+01]]
     nfev: 30
     njev: 30
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>


In [18]:
opt_beale.x

array([[ 3.06892363,  3.95908119,  3.50500753,  2.93561658,  2.45373251,
         3.7763075 ,  2.57362673,  3.6812923 ,  2.16837429,  3.36963247,
         2.53521766,  3.52705258,  3.1304042 ,  3.00029069,  2.34885001,
         3.4875092 ,  2.76881897,  3.05669909,  2.08772764,  3.63856801,
         2.51954147,  2.97100058,  3.27201485,  2.73253786,  3.97214418,
         2.5637877 ,  2.70534359,  3.88198055,  2.36844032,  3.78236555],
       [-0.62253996, -0.68008723, -0.4915677 , -0.47415555, -0.47763037,
        -0.70481421, -0.90967047, -0.24249928, -0.65934021, -0.0539378 ,
        -0.50141662, -0.78252695, -0.95996856, -0.63655167, -0.290179  ,
        -0.24366023, -0.90890325, -0.31464346, -0.07387695, -0.09005485,
        -0.22303191, -0.83201079, -0.4672728 , -0.11113677, -0.14724142,
        -0.32394522, -0.18373587, -0.5883357 , -0.30379142, -0.73581555]])

In [19]:
np.mean(opt_beale.x, axis=1)

array([ 3.06139631, -0.46781139])

In [20]:
np.std(opt_beale.x, axis=1)

array([0.55687515, 0.26991453])