- import some functions from stochopy to test the code

In [1]:
# python lbfgsb works with numpy arrays
import numpy as np
from pyrtid.inverse import minimize_lbfgsb
from scipy.optimize import minimize

- First example: min x^{\mathrm{T}}x such that x>=1. Optimal solution hits the boundary.

In [2]:
def quad(x):
    # return x.dot(x)
    return 10 * x[0] ** 2 + x[1] ** 2


def grad_quad(x):
    return np.array([20 * x[0], 2 * x[1]])


def fun_and_grad(x):
    return quad(x), grad_quad(x)


ftol = 1e-5
gtol = 1e-5
l = np.array([1.0, 1.0])
u = np.array([np.inf, np.inf])
bounds = np.array((l, u)).T
x0 = np.array([5, 5])

In [3]:
bounds[0]

array([ 1., inf])

### New implementation

In [4]:
print("====================== Quadratic example ======================")
opt_quad = minimize_lbfgsb(
    x0=x0, fun=quad, jac=grad_quad, bounds=bounds, ftol=ftol, gtol=gtol, iprint=101
)
print("")
print("")
xOpt = np.array([1, 1])
theoOpt = {"x": xOpt, "f": quad(xOpt), "df": grad_quad(xOpt)}
print("Theoretical optimal value: ")
print(theoOpt)
print("Optimal value found: ")
print(opt_quad)

====================== Quadratic example ======================
RUNNING THE L-BFGS-B CODE
           * * *
Machine precision = 2.220446049250313e-16
N = 	2	M = 	10
At X0, 0 variables are exactly at the bounds
At iterate 0 , f= 275.0 , |proj g|= 4.0

ITERATION 1

---------------- CAUCHY entered-------------------
There are 2 breakpoints 
Piece    , 1,  --f1, f2 at start point , -10100.0 , 10100.0
Distance to the next break point =  0.04
Distance to the stationary point =  1.0
Variable  1 is fixed.
Piece    , 2,  --f1, f2 at start point , -96.0 , 1.0100000000000002e-26
Distance to the next break point =  0.36000000000000004
Distance to the stationary point =  9.504950495049504e+27
Variable  2 is fixed.
GCP found in this segment
Cauchy X =  [1. 1.]
---------------- exit CAUCHY----------------------
0 variables are free at GCP, iter = 1
LINE SEARCH  0 times; norm of step = 0.17677669529663687
Iteration #0 (max: 50): ||x||=4.293e+00, f(x)=2.027e+02, ||jac(x)||=8.586e+01, cdt_arret=3.293e+00

### Scipy

In [5]:
minimize(
    quad,
    x0,
    jac=grad_quad,
    bounds=bounds,
    method="l-bfgs-b",
    options={"gtol": gtol, "ftol": ftol, "disp": 200, "iprint": 200},
)

RUNNING THE L-BFGS-B CODE


  message: CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
  success: True
   status: 0
      fun: 11.0
        x: [ 1.000e+00  1.000e+00]
      nit: 2
      jac: [ 2.000e+01  2.000e+00]
     nfev: 3
     njev: 3
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>


           * * *

Machine precision = 2.220D-16
 N =            2     M =           10

 L =  1.0000D+00  1.0000D+00

X0 =  5.0000D+00  5.0000D+00

 U =  0.0000D+00  0.0000D+00

At X0         0 variables are exactly at the bounds

At iterate    0    f=  2.75000D+02    |proj g|=  4.00000D+00


ITERATION     1

---------------- CAUCHY entered-------------------
 There are            2   breakpoints 

Piece      1 --f1, f2 at start point  -1.0100D+04  1.0100D+04
Distance to the next break point =   4.0000D-02
Distance to the stationary point =   1.0000D+00
 Variable             1   is fixed.

Piece      2 --f1, f2 at start point  -9.6000D+01  1.0000D+02
Distance to the next break point =   3.6000D-01
Distance to the stationary point =   9.6000D-01
 Variable             2   is fixed.
Cauchy X =  
      1.0000D+00  1.0000D+00

---------------- exit CAUCHY----------------------

           0  variables are free at GCP            1
 LINE SEARCH           0  times; norm of step =    1.0000000

## Second example : min Rosenbrock function

In [6]:
def rosenbrock(x):
    return 100 * (x[1] - x[0] ** 2) ** 2 + (1 - x[0]) ** 2


def grad_rosenbrock(x):
    g = np.empty(x.size)
    g[0] = 400 * x[0] * (x[0] ** 2 - x[1]) + 2 * (x[0] - 1)
    g[1] = 200 * (-x[0] ** 2 + x[1])
    return g


l = np.array([-2, -2])
u = np.array([2, 2])
bounds = np.array((l, u)).T
# x0 = np.array([0.12, 0.12])
x0 = np.array([-0.8, -1])

### New implementation

In [7]:
np.finfo(1.0).resolution * 1e7

1e-08

In [8]:
opt_rosenbrock = minimize_lbfgsb(
    x0=x0,
    fun=rosenbrock,
    jac=grad_rosenbrock,
    bounds=bounds,
    maxcor=5,
    ftol=ftol,
    gtol=gtol,
    iprint=101,
    ftol_linesearch=1e-3,
    gtol_linesearch=0.9,
    xtol_linesearch=0.1,
)
print("")
print("")
theoOpt = {"x": np.array([1, 1]), "f": 0, "df": grad_rosenbrock(np.array([1, 1]))}
print("Theoretical optimal value: ")
print(theoOpt)
print("Optimal value found: ")

RUNNING THE L-BFGS-B CODE
           * * *
Machine precision = 2.220446049250313e-16
N = 	2	M = 	5
At X0, 0 variables are exactly at the bounds
At iterate 0 , f= 272.20000000000005 , |proj g|= 3.0

ITERATION 1

---------------- CAUCHY entered-------------------
There are 2 breakpoints 
Piece    , 1,  --f1, f2 at start point , -386790.5600000001 , 386790.5600000001
Distance to the next break point =  0.00529901589704769
Distance to the stationary point =  1.0
Variable  1 is fixed.
Piece    , 2,  --f1, f2 at start point , -107013.91067373205 , 3.8679056000000014e-25
Distance to the next break point =  0.0038473255663669433
Distance to the stationary point =  2.7667146445800543e+29
Variable  2 is fixed.
GCP found in this segment
Cauchy X =  [2. 2.]
---------------- exit CAUCHY----------------------
0 variables are free at GCP, iter = 1
LINE SEARCH  0 times; norm of step = 0.24368508941428965
Iteration #0 (max: 50): ||x||=2.689e-01, f(x)=9.246e+00, ||jac(x)||=5.656e+01, cdt_arret=2.269e+00

LinAlgError: 3-th leading minor of the array is not positive definite

In [ ]:
print(opt_rosenbrock)

  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 1.7818523593938084e-06
        x: [ 9.999e-01  9.999e-01]
      nit: 23
      jac: [-5.341e-02  2.659e-02]
     nfev: 29
     njev: 29
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>


### Scipy

In [ ]:
opt_rosenbrock_sp = minimize(
    rosenbrock,
    x0,
    jac=grad_rosenbrock,
    bounds=bounds,
    method="l-bfgs-b",
    options={"gtol": gtol, "ftol": ftol, "iprint": 100, "maxcor": 5},
)

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            2     M =            5

At X0         0 variables are exactly at the bounds

At iterate    0    f=  2.72200D+02    |proj g|=  3.00000D+00


ITERATION     1

---------------- CAUCHY entered-------------------
 There are            2   breakpoints 

Piece      1 --f1, f2 at start point  -3.8679D+05  3.8679D+05
Distance to the next break point =   5.2990D-03
Distance to the stationary point =   1.0000D+00
 Variable             1   is fixed.

Piece      2 --f1, f2 at start point  -1.0701D+05  1.0758D+05
Distance to the next break point =   3.8473D-03
Distance to the stationary point =   9.9470D-01
 Variable             2   is fixed.

---------------- exit CAUCHY----------------------

           0  variables are free at GCP            1
 LINE SEARCH           1  times; norm of step =    2.0052498411651980     

At iterate    1    f=  2.23351D+00    |proj g|=  2.46595D+00


ITERATION     2

----------

In [ ]:
opt_rosenbrock_sp

  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 3.873869632030741e-07
        x: [ 9.994e-01  9.988e-01]
      nit: 19
      jac: [-1.603e-03  1.794e-04]
     nfev: 24
     njev: 24
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>

## Third example : min Beale function

In [ ]:
def beale(x):
    return (
        (1.5 - x[0] + x[0] * x[1]) ** 2
        + (2.25 - x[0] + x[0] * x[1] ** 2) ** 2
        + (2.625 - x[0] + x[0] * x[1] ** 3) ** 2
    )


def grad_beale(x):
    y1 = x[1]
    y2 = y1 * y1
    y3 = y2 * y1
    f1 = 1.5 - x[0] + x[0] * y1
    f2 = 2.25 - x[0] + x[0] * y2
    f3 = 2.625 - x[0] + x[0] * y3

    return np.array(
        [
            2 * (y1 - 1) * f1 + 2 * (y2 - 1) * f2 + 2 * (y3 - 1) * f3,
            2 * x[0] * f1 + 4 * x[0] * y1 * f2 + 6 * x[0] * y2 * f3,
        ]
    )


ftol = 1e-14
gtol = 1e-10
l = -4.5 * np.ones(2)
u = -l
bounds = np.array((l, u)).T
x0 = np.array([2.5, -1.3])

### New implementation

In [ ]:
opt_beale = minimize_lbfgsb(
    x0=x0, fun=beale, jac=grad_beale, bounds=bounds, ftol=ftol, gtol=gtol
)
print("")
print("")
theoOpt = {
    "x": np.array([3, 0.5]),
    "f": beale(np.array([3, 0.5])),
    "df": grad_beale(np.array([3, 0.5])),
}
print("Theoretical optimal value: ")
print(theoOpt)
print("Optimal value found: ")

K11     = [[343.56344264]]
K11 bis = [[343.56344264]]
K11     = [[1.42585345e+03 7.88450811e+00]
 [7.88450811e+00 1.04522466e-01]]
K11 bis = [[1.42585345e+03 7.88450811e+00]
 [7.88450811e+00 1.04522466e-01]]
K11     = [[2.05761871e+03 1.18564964e+01 3.77709427e+01]
 [1.18564964e+01 1.30850171e-01 2.53574081e-01]
 [3.77709427e+01 2.53574081e-01 1.64120549e+00]]
K11 bis = [[2.05761871e+03 1.18564964e+01 3.77709427e+01]
 [1.18564964e+01 1.30850171e-01 2.53574081e-01]
 [3.77709427e+01 2.53574081e-01 1.64120549e+00]]
K11     = [[4.75668398e+03 2.88258623e+01 9.18298250e+01 3.35917898e+01]
 [2.88258623e+01 2.43328967e-01 6.16496752e-01 2.20218062e-01]
 [9.18298250e+01 6.16496752e-01 2.81567623e+00 7.08713559e-01]
 [3.35917898e+01 2.20218062e-01 7.08713559e-01 5.08779599e-01]]
K11 bis = [[4.75668398e+03 2.88258623e+01 9.18298250e+01 3.35917898e+01]
 [2.88258623e+01 2.43328967e-01 6.16496752e-01 2.20218062e-01]
 [9.18298250e+01 6.16496752e-01 2.81567623e+00 7.08713559e-01]
 [3.35917898e+01 2.2

In [ ]:
print(opt_beale)

  message: CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
  success: True
   status: 1
      fun: 6.910751138008978e-24
        x: [ 3.000e+00  5.000e-01]
      nit: 16
      jac: [-5.141e-12  2.368e-11]
     nfev: 19
     njev: 19
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>


### Scipy

In [ ]:
opt_beale_sp = minimize(
    beale,
    x0,
    jac=grad_beale,
    bounds=bounds,
    method="l-bfgs-b",
    options={"gtol": gtol, "ftol": ftol},
)

In [ ]:
opt_beale_sp

  message: CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH
  success: True
   status: 0
      fun: 1.4337068336583181e-21
        x: [ 3.000e+00  5.000e-01]
      nit: 16
      jac: [-7.089e-11  1.797e-10]
     nfev: 20
     njev: 20
 hess_inv: <2x2 LbfgsInvHessProduct with dtype=float64>

- Comparision of convergence